<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => '',
  'Customer Information' => 'Thông tin khách hàng',
  'Are you sure you want to delete this item?' => 'Có chắc chắn là xóa mục này không?',
  'CSR' => 'YÊU CẦU XỬ LÝ SỰ CỐ - CSR',
'CSR Information' => 'Thông tin sự cố',
  'Cause' => 'Nguyên nhân lỗi',
  'Create' => 'Tạo',
  'Create CSR' => 'Tạo CSR',
  'Create RMA' => 'Tạo RMA',
  'Create {modelClass}' => 'Tạo {modelClass}',
  'Created At' => 'Tạo lúc',
  'Created By' => 'Tạo bởi',
  'Customer Company' => 'Công ty Khách hàng',
  'Customer Email' => 'Email Khách hàng',
  'Customer Fullname' => 'Họ Tên Khách hàng',
  'Customer Phone' => 'Điện thoại Khách hàng',
  'Delete' => 'Xóa',
  'Detail' => 'Chi tiết',
  'Fixed Begin' => 'Thời gian khắc phục sự cố tạm thời',
  'Fixed End' => 'Thời gian khắc phục sự cố hoàn toàn',
  'Hardware Part' => 'Part Number',
  'Hardware Serial' => 'Serial Number',
  'Hardware Type' => 'Loại phần cứng',
  'Priority' => 'Mức độ sự cố',
  'RMA' => 'YÊU CẦU BẢO HÀNH PHẦN CỨNG - RMA',
  'Replied At' => 'Thời gian phản hồi khách hàng',
  'Requested At' => 'Thời gian nhận thông tin lỗi',
  'Reset' => 'Đặt lại',
  'Search' => 'Tìm kiếm',
  'Site' => 'Vị trí đặt thiết bị',
  'Solution' => 'Giải pháp xử lý',
  'Status' => 'Tình trạng xử lý',
  'Suggestion' => 'Đề nghị của khách hàng',
  'System' => 'Hệ thống gặp sự cố',
  'Tickets' => 'Ticket',
  'Title' => 'Tiêu đề',
  'Type' => 'Loại',
  'Update' => 'Sửa',
  'Update {modelClass}: ' => 'Sửa {modelClass}:',
  'Updated At' => 'Sửa lúc',
  'Updated By' => 'Sửa bởi',
);
